= Lab 3: Properties

== part 1: Pick up where we left off
. navigate to your project from lab 2
. alternatively, you can go to start.spring.io and
.. go through all the steps from lab 1
.. no additional dependencies are necessary for this lab


== part 2: create some properties files
. in `src/main/resources`
. add this to `application.properties`
+
....
greeter.details.name=DefaultDISH
....
. create the file `application-p1.properties` and add:
+
....
greeter.details.name=P1_DISH
....
. create the file `application-p2.properties` and add:
+
....
greeter.details.name=P2_DISH
....
. create the file `application-cloud.properties` and add:
+
....
greeter.details.name=P1_IN_THE_CLOUD
....
. create the file `application-p3.yml` and add:
+
....
greeter:
  details:
    name: P3_DISH_FROM_YAML
....
. create the `GreeterSettings` class alongside your other classes.  Its contents would look something like this:
+
....
package bootworkshop.pivotal.io;

import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * Created by rhardt on 9/21/16.
 */
@ConfigurationProperties(prefix = "greeter.details")
public class GreeterSettings {

    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
....
. note that we're telling the class to look in all the Spring property sources for properties beginning with _greeter.details_ and then populate its bean values with anything after that prefix.
so _greeter.details.name_ will populate GreeterSettings' _name_ property.
. autowire the GreeterSettings class into our HelloController
+
....
@RestController
@EnableConfigurationProperties(GreeterSettings.class)
public class HelloController {


    @Autowired
    private GreeterSettings greeterSettings;

    @RequestMapping("/")
    public String sayHello(){
        return String.format("Hello %s!", greeterSettings.getName());
    }
....
. notice the 3 changes
.. the `@EnableConfigurationProperties(GreeterSettings.class)` annotation
.. the `@Autowired` GreeterSettings instance
.. modified `sayHello()` method to use the property.

== part 3: running the app
. stop any running versions of the app
. `./mvnw spring-boot:run`
. visit http://localhost:8080/
. what do you see?
. stop the app and restart it with `./mvnw spring-boot:run -Drun.profiles=p1`
. refresh the web browser
. stop the app and restart it with `./mvnw spring-boot:run -Drun.profiles=p2`
. refresh the web browser
. stop the app and restart it with `./mvnw spring-boot:run -Drun.profiles=p3`
. refresh the web browser.  Did it pick up the .yml?

== part 4:  cf push

. repackage `./mvnw clean package`
. push your app:  `cf push`
.. visit http://hello-your-random.yoursite.com/
.. which properties file did it pick up?
.. do you remember specifying a profile anywhere to cloud foundry?
. In production, we probably don't want our settings in properties files.  They should be runtime environment variables.
.. Try this command `cf set-env hello GREETER_DETAILS_NAME Dish_From_The_Environment`
.. Then `cf restage hello`
.. refresh the web browser again.  What do you see?  An you should see an *opinionated runtime*!






