= Lab 5: Spring Data REST

== part 1: we need Spring Boot's starter for Data REST
. navigate to your project from lab 4
. open the `pom.xml` from lab 4
. add the following dependency
+
[source, xml, numbered]
---------------------------------------------------------------------
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-rest</artifactId>
</dependency>
---------------------------------------------------------------------
+
.

== part 2: expose our MovieRepository
. add `@RepositoryRestResource` annotation to *_MovieRepository_*
.. add attribute `collectionResourceRel = "movies"` to @RepositoryRestResource annotation
.. add attribute `path = "movies"` to @RepositoryRestResource annotation
. stop your previous version if it is still running
 `./mvnw spring-boot:run`
. visit http://localhost:8080/movies
. follow the various links

== part 3: let their be data
from part 2 we can see there's no data
. POST data to the MovieRepository RESTful service +
`curl -i -X POST -H "Content-Type:application/json" -d '{"title" : "Descpicalble Me", "year" : "2010", "rated" : "PG", "released" : "09 Jul 2010", "runtime" : "95 min" }'  http://localhost:8080/movies/` +
[%hardbreaks]
. visit http://localhost:8080/movies

== part 4: open the flood gates
let's preload some data +
. copy labs/lab5/import.sql to src/main/resources +
. stop your previous version if it is still running +
 `./mvnw spring-boot:run` +
. visit http://localhost:8080/movies +
. follow the various links

== part 5: i failed to search for you
let's fix search, in case you noticed there were errors +
. visit http://localhost:8080/movies/search/findByTitle?title=Minions +
. let's modify *_MovieRepository_*
.. add @Param("title") as in `List<Movie> findByTitle(@Param("title") String title);` +
.. add @Param ("rated") as in `List<Movie> findByRated(@Param("rated") String rated);` +
.. add @Param ("genre") as in `List<Movie> findByGenreStartsWith(@Param("genre") String genre);` + 
`./mvnw spring-boot:run`
. visit http://localhost:8080/movies/search/findByTitle?title=Minions

== part 6: pagination
let's enable pagination
. change CrudRepository in *_MovieRepository_* to use PagingAndSortingRepository
. change return type from List<Movie> to Page<Movie>
. add extra argument to each findBy method as in `@Param("title") String title, Pageable pageable`
. should now look like
[source, java, numbered]
---------------------------------------------------------------------
import io.pivotal.domain.Movie;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

@RepositoryRestResource(collectionResourceRel = "movies", path = "movies")
public interface MovieRepository extends PagingAndSortingRepository<Movie, Long> {

    Page<Movie> findByTitle(@Param("title") String title, Pageable pageable);

    Page<Movie> findByRated(@Param("rated") String rated, Pageable pageable);

    Page<Movie> findByGenreStartsWith(@Param("genre") String genre, Pageable pageable);

}
---------------------------------------------------------------------
+ 
`./mvnw spring-boot:run`
. visit http://localhost:8080/movies/
. scroll to bottom of page to see pagination enabled
. now visit http://localhost:8080/movies/search/findByGenreStartsWith?genre=Animation&sort=year
. verify sort order by year movie was released